version: '3.9'

services:
  db:
    image: postgres
    container_name: portfolio-db
    ports:
      - 5432:5432
    volumes:
      - ~/dockerdev/pgsql:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: pgtestpassword
        POSTGRES_USER: portfolio_user
        POSTGRES_DB: portfolio_db
  

